# docker run -dit --name my-apache-app -p 8080:80 -v "$PWD":/usr/local/apache2/htdocs/ httpd:2.4

version: '3.7'
services:
  app:
    image: httpd:2.4
    volumes:
      - ./html:/usr/local/apache2/htdocs
    ports:
      - "8080:80"
